// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocrataCache.DatasetManager;
using SocrataCache.Managers;

#nullable disable

namespace SocrataCache.DatasetManager.Migrations
{
    [DbContext(typeof(ManagerContext))]
    [Migration("20250305140404_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SocrataCache.Old.DatasetManager.Models.DatasetModel", b =>
                {
                    b.Property<string>("DatasetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DatasetId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReferenceDate");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ResourceId");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("DatasetId");

                    b.ToTable("Dataset");
                });
#pragma warning restore 612, 618
        }
    }
}
