services:
  socratacache:
    image: socratacache
    build:
      context: .
      dockerfile: SocrataCache/Dockerfile
    environment:
      SOCRATACACHE_CONFIG_FILE: /app/sc-config.json
      SOCRATACACHE_DB_FILE_PATH: /app/socratacache.db
      SOCRATACACHE_DOWNLOADS_ROOT_PATH: /app/scdatasets
    volumes:
      - type: bind
        source: ./sc-config.json
        target: /app/sc-config.json
      - ./scdatasets:/app/scdatasets
    ports:
      - 8080:8080
  gossa:
    image: pldubouilh/gossa
    volumes:
      - ./scdatasets:/shared
    ports:
      - 8081:8001
    environment:
      - READONLY=true